const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const canvas=$('#canvas'),ctx=canvas.getContext('2d'),input=$('#photoInput'),W=2525,H=1894,VERSION='8.0.0';
const charFiles={lelepop:[1,2,3,4,5,6].map(n=>`lelepop_0${n}.png`),buttscaler:[1,2,3,4,5,6].map(n=>`buttscaler_0${n}.png`),zumba:[1,2,3,4,5,6].map(n=>`zumba_0${n}.png`),'zumba-camp':[1,2,3,4,5,6].map(n=>`zumba_camp_0${n}.png`)};
const titles={lelepop:['LELEPOP','LELE POP','LELEPOP DANCE','DANCE MODE','LELEPOP ✦'],buttscaler:['BUTTSCALER','GLUTE & LEG','POWER MODE','BUTTSCALER ✦','STRONG & SHINE'],zumba:['ZUMBA','ZUMBA DANCE','ZUMBA!','ZUMBA ✦','MOVE · ZUMBA'],'zumba-camp':['ZUMBA CLASS','ZUMBA BREAKDOWN','ZUMBA PRACTICE','ZUMBA SESSION','BREAK IT DOWN']};
const styles={energetic:{label:'活力',p:['#ff2f91','#7658ff'],st:['✦','⚡','♪','✨']},cool:{label:'酷飒',p:['#2f63ff','#171723'],st:['⚡','★','✦','♫']},cute:{label:'可爱',p:['#ff62ad','#9a73ff'],st:['♡','🐻','🐰','✨']},clean:{label:'清爽',p:['#5d7dff','#48cbb3'],st:['✦','·','♡','✨']},y2k:{label:'Y2K',p:['#ff3fa4','#6c5cff'],st:['✦','★','♡','♫']}};
let photo=null,course=localStorage.popshotLastCourse||'zumba',beauty=+(localStorage.popshotLastBeauty||38),visualStyle=localStorage.popshotStyle||'energetic',density='normal';
let photoZoom=1,photoDX=0,photoDY=0,photoAdjust=false,boxesDetected=[],charIndex=0,titleIndex=0,frameIndex=1,stickerIndex=0,layoutIndex=1,selected=null,dragging=false,dragOffset={x:0,y:0},locked=null,undo=[],redo=[],loaded={},zOrder=['title','character','logo','sticker'];
let layers={};
function resetLayers(){layers={title:{x:90,y:72,scale:1,anchor:'left',visible:true},character:{x:W-560,y:H-650,scale:1,visible:true},logo:{x:W-550,y:H-190,scale:1.15,visible:true},sticker:{x:W-125,y:90,scale:1,visible:true}}}
resetLayers();
function asset(c,i){return `./public/assets/characters/${c}/${charFiles[c][i]}`}; function load(path){return loaded[path]||(loaded[path]=new Promise((r,j)=>{let im=new Image;im.onload=()=>r(im);im.onerror=j;im.src=path}))}
function holidayStickers(){let d=new Date(),m=d.getMonth()+1,day=d.getDate(),y=d.getFullYear();if(m===12&&day>=20)return ['🎄','🎅','❄️','🎁'];if(m===10&&day>=25)return ['🎃','👻','🦇'];if(m===2&&day>=10&&day<=16)return ['💘','💗','🌹'];if(y===2026&&m===9&&day>=23&&day<=27)return ['🌕','🐇','🥮'];if(y===2027&&m===2&&day>=4&&day<=10)return ['🧧','🏮','🐉'];return null}
function stickerPool(){return holidayStickers()||styles[visualStyle].st}
async function detectPeople(img){boxesDetected=[];$('#detectStatus').textContent='正在识别合照主体…';try{const mod=await import('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/+esm');const vision=await mod.FilesetResolver.forVisionTasks('https://cdn.jsdelivr.net/npm/@mediapipe/tasks-vision@0.10.22/wasm');const fd=await mod.FaceDetector.createFromOptions(vision,{baseOptions:{modelAssetPath:'https://storage.googleapis.com/mediapipe-models/face_detector/blaze_face_short_range/float16/latest/blaze_face_short_range.tflite'},runningMode:'IMAGE',minDetectionConfidence:.35});const r=fd.detect(img);boxesDetected=(r.detections||[]).map(d=>d.boundingBox).map(b=>({x:b.originX,y:b.originY,w:b.width,h:b.height}));fd.close()}catch(e){if('FaceDetector'in window)try{let f=await new FaceDetector({fastMode:true,maxDetectedFaces:40}).detect(img);boxesDetected=f.map(x=>({x:x.boundingBox.x,y:x.boundingBox.y,w:x.boundingBox.width,h:x.boundingBox.height}))}catch(_){}}
$('#detectStatus').textContent=boxesDetected.length?`已识别 ${boxesDetected.length} 位主体 · 可手动调整裁剪`:'已启用智能裁剪 · 可手动调整照片';return boxesDetected}
function smartCrop(){let iw=photo.width,ih=photo.height,tr=W/H,sw,sh,cx=iw/2,cy=ih/2;if(boxesDetected.length){let avgH=boxesDetected.reduce((s,b)=>s+b.h,0)/boxesDetected.length;let x1=Math.min(...boxesDetected.map(b=>b.x)),x2=Math.max(...boxesDetected.map(b=>b.x+b.w)),y1=Math.min(...boxesDetected.map(b=>b.y)),y2=Math.max(...boxesDetected.map(b=>b.y+b.h));let left=Math.max(0,x1-avgH*.9),right=Math.min(iw,x2+avgH*.9),top=Math.max(0,y1-avgH*1.0),bottom=Math.min(ih,y2+avgH*6.2);cx=(left+right)/2;cy=(top+bottom)/2;sw=right-left;sh=bottom-top;if(sw/sh<tr)sw=sh*tr;else sh=sw/tr;sw=Math.min(iw,sw);sh=Math.min(ih,sh)}else{if(iw/ih>tr){sh=ih;sw=ih*tr}else{sw=iw;sh=iw/tr}}
let z=Math.max(1,photoZoom);sw/=z;sh/=z;let sx=cx-sw/2-photoDX*iw/W,sy=cy-sh/2-photoDY*ih/H;sx=Math.max(0,Math.min(iw-sw,sx));sy=Math.max(0,Math.min(ih-sh,sy));return{sx,sy,sw,sh}}
function faceZones(){if(!photo)return[];let c=smartCrop(),sx=W/c.sw,sy=H/c.sh;return boxesDetected.map(b=>({x:(b.x-c.sx)*sx,y:(b.y-c.sy)*sy,w:b.w*sx,h:b.h*sy})).filter(b=>b.x+b.w>0&&b.y+b.h>0&&b.x<W&&b.y<H)}
function overlap(a,b){return Math.max(0,Math.min(a.x+a.w,b.x+b.w)-Math.max(a.x,b.x))*Math.max(0,Math.min(a.y+a.h,b.y+b.h)-Math.max(a.y,b.y))}
function crowd(){let n=boxesDetected.length;if(n>=10)return'high';if(n>=6)return'mid';return'low'}
function autoPlace(){let cand=[{tx:80,ta:'left',cx:W-560,lx:W-550},{tx:W-80,ta:'right',cx:65,lx:70}],zones=faceZones(),best=cand[0],score=1e30;for(let c of cand){let tb={x:c.ta==='left'?c.tx:c.tx-1150,y:60,w:1150,h:280},cb={x:c.cx,y:H-670,w:520,h:650},lb={x:c.lx,y:H-190,w:500,h:120};let s=zones.reduce((n,z)=>n+overlap(tb,z)+1.5*overlap(cb,z)+1.2*overlap(lb,z),0);if(s<score){score=s;best=c}}layers.title.x=best.tx;layers.title.y=65;layers.title.anchor=best.ta;layers.character.x=best.cx;layers.character.y=H-650;layers.logo.x=best.lx;layers.logo.y=H-190;let c=crowd();if(c==='high'){layers.character.scale=.72;layers.logo.scale=.95;layers.sticker.visible=false}else if(c==='mid'){layers.character.scale=.86;layers.logo.scale=1.05;layers.sticker.visible=density!=='simple'}else{layers.character.scale=density==='rich'?1.12:1;layers.logo.scale=density==='simple'?1.02:1.15;layers.sticker.visible=density!=='simple'}}
function drawPhoto(){let c=smartCrop(),b=beauty/100;ctx.save();ctx.filter=`brightness(${1+b*.10}) contrast(${1+b*.08}) saturate(${1+b*.14})`;ctx.drawImage(photo,c.sx,c.sy,c.sw,c.sh,0,0,W,H);ctx.restore()}
function rr(x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r)}
function drawFrame(){if(!frameIndex)return;ctx.save();let p=styles[visualStyle].p;if(frameIndex===1){ctx.strokeStyle='rgba(255,255,255,.78)';ctx.lineWidth=10}else if(frameIndex===2){ctx.strokeStyle=p[0];ctx.globalAlpha=.55;ctx.lineWidth=13}else{let g=ctx.createLinearGradient(0,0,W,H);g.addColorStop(0,p[0]);g.addColorStop(1,p[1]);ctx.strokeStyle=g;ctx.globalAlpha=.7;ctx.lineWidth=14}ctx.strokeRect(30,30,W-60,H-60);ctx.restore()}
function drawTitle(){let l=layers.title;if(!l.visible)return null,t=titles[course][titleIndex%titles[course].length],p=styles[visualStyle].p,size=168*l.scale;ctx.save();ctx.textAlign=l.anchor;ctx.textBaseline='top';ctx.lineJoin='round';ctx.font=`900 ${size}px Arial Black,Impact,sans-serif`;let w=Math.min(1500,ctx.measureText(t).width+70),x=l.x,y=l.y;ctx.strokeStyle='rgba(255,255,255,.95)';ctx.lineWidth=26*l.scale;ctx.strokeText(t,x,y);let g=ctx.createLinearGradient(l.anchor==='left'?x:x-w,y,l.anchor==='left'?x+w:x,y);g.addColorStop(0,p[0]);g.addColorStop(1,p[1]);ctx.fillStyle=g;ctx.fillText(t,x,y);ctx.font=`800 ${40*l.scale}px sans-serif`;ctx.fillStyle='white';ctx.shadowColor='#0007';ctx.shadowBlur=9;let sub=course==='buttscaler'?'POWER · GLUTE · LEG':course==='zumba-camp'?'PRACTICE · BREAKDOWN':'MOVE · SMILE · ENJOY';ctx.fillText(sub,x,y+178*l.scale);ctx.restore();return{x:l.anchor==='left'?x:x-w,y,w,h:250*l.scale}}
async function drawCharacter(){let l=layers.character;if(!l.visible)return null,im=await load(asset(course,charIndex)),mw=540*l.scale,mh=650*l.scale,s=Math.min(mw/im.width,mh/im.height),w=im.width*s,h=im.height*s;l.w=w;l.h=h;ctx.save();ctx.shadowColor='#20152f44';ctx.shadowBlur=18;ctx.shadowOffsetY=7;ctx.drawImage(im,l.x,l.y,w,h);ctx.restore();return{x:l.x,y:l.y,w,h}}
function drawLogo(){let l=layers.logo;if(!l.visible)return null,p=styles[visualStyle].p,w=430*l.scale,h=112*l.scale;l.w=w;l.h=h;ctx.save();rr(l.x,l.y,w,h,40*l.scale);let g=ctx.createLinearGradient(l.x,l.y,l.x+w,l.y+h);g.addColorStop(0,p[0]);g.addColorStop(1,p[1]);ctx.fillStyle=g;ctx.fill();ctx.strokeStyle='rgba(255,255,255,.75)';ctx.lineWidth=4;ctx.stroke();ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillStyle='white';ctx.font=`900 ${44*l.scale}px Arial Black,sans-serif`;let main=course==='zumba-camp'?'ZUMBA':course==='buttscaler'?'BUTTSCALER':course==='lelepop'?'LELEPOP':'ZUMBA';ctx.fillText(main,l.x+w/2,l.y+h*.44);ctx.font=`700 ${19*l.scale}px sans-serif`;let sub=course==='zumba-camp'?'BREAKDOWN CLASS':course==='buttscaler'?'GLUTE & LEG':'CLASS';ctx.fillText(sub,l.x+w/2,l.y+h*.78);ctx.restore();return{x:l.x,y:l.y,w,h}}
function drawSticker(){let l=layers.sticker;if(!l.visible)return null,s=stickerPool()[stickerIndex%stickerPool().length],font=66*l.scale;l.w=font*1.3;l.h=font*1.3;ctx.save();ctx.globalAlpha=.9;ctx.font=`${font}px Apple Color Emoji,Segoe UI Emoji,sans-serif`;ctx.fillText(s,l.x,l.y+font);ctx.restore();return{x:l.x,y:l.y,w:l.w,h:l.h}}
function selectBox(b,n){if(selected!==n||!b)return;ctx.save();ctx.strokeStyle='#805cff';ctx.lineWidth=5;ctx.setLineDash([14,10]);ctx.strokeRect(b.x-8,b.y-8,b.w+16,b.h+16);ctx.restore()}
async function render(){ctx.clearRect(0,0,W,H);if(!photo)return;$('#placeholder').classList.add('hidden');drawPhoto();let wash=ctx.createLinearGradient(0,0,W,H);wash.addColorStop(0,'rgba(90,60,170,.025)');wash.addColorStop(1,'rgba(255,70,145,.02)');ctx.fillStyle=wash;ctx.fillRect(0,0,W,H);drawFrame();let b={};for(let n of zOrder){if(n==='title')b.title=drawTitle();if(n==='character')b.character=await drawCharacter();if(n==='logo')b.logo=drawLogo();if(n==='sticker')b.sticker=drawSticker()}Object.entries(b).forEach(([n,x])=>selectBox(x,n));updateCheck()}
function state(){return JSON.stringify({layers,course,beauty,visualStyle,density,photoZoom,photoDX,photoDY,charIndex,titleIndex,frameIndex,stickerIndex,layoutIndex,zOrder})}function push(){undo.push(state());if(undo.length>30)undo.shift();redo=[]}function restore(raw){let s=JSON.parse(raw);Object.assign(window,s);layers=s.layers;course=s.course;beauty=s.beauty;visualStyle=s.visualStyle||'energetic';density=s.density||'normal';photoZoom=s.photoZoom||1;photoDX=s.photoDX||0;photoDY=s.photoDY||0;charIndex=s.charIndex;titleIndex=s.titleIndex;frameIndex=s.frameIndex;stickerIndex=s.stickerIndex;layoutIndex=s.layoutIndex;zOrder=s.zOrder||zOrder;syncUI();render()}
function hist(){try{return JSON.parse(localStorage.popshotHistory||'[]')}catch{return[]}}function comboKey(){return[course,charIndex,titleIndex,frameIndex,stickerIndex,layoutIndex,visualStyle].join('|')}function pickCombo(){let now=Date.now(),h=hist().filter(x=>x.time>now-14*864e5),wd=new Date().getDay();for(let i=0;i<120;i++){charIndex=Math.floor(Math.random()*6);titleIndex=Math.floor(Math.random()*titles[course].length);frameIndex=Math.floor(Math.random()*4);stickerIndex=Math.floor(Math.random()*stickerPool().length);layoutIndex=Math.floor(Math.random()*3);let k=comboKey();if(!h.some(x=>x.key===k)&&!h.some(x=>x.course===course&&x.weekday===wd&&x.key===k)){h.push({key:k,course,time:now,weekday:wd});localStorage.popshotHistory=JSON.stringify(h.slice(-160));break}}}
function syncUI(){$$('[data-course]').forEach(b=>b.classList.toggle('active',b.dataset.course===course));$$('[data-beauty]').forEach(b=>b.classList.toggle('on',+b.dataset.beauty===beauty));$$('[data-style]').forEach(b=>b.classList.toggle('on',b.dataset.style===visualStyle));$$('[data-density]').forEach(b=>b.classList.toggle('on',b.dataset.density===density));$('#beautyText').textContent=beauty===0?'原图':beauty>=60?'活力':'自然'}
function point(e){let r=canvas.getBoundingClientRect(),p=e.touches?e.touches[0]:e;return{x:(p.clientX-r.left)*W/r.width,y:(p.clientY-r.top)*H/r.height}}function currentBoxes(){let t=layers.title,c=layers.character,l=layers.logo,s=layers.sticker;return{title:{x:t.anchor==='left'?t.x:t.x-1200,y:t.y,w:1200,h:270},character:{x:c.x,y:c.y,w:c.w||500,h:c.h||620},logo:{x:l.x,y:l.y,w:l.w||430,h:l.h||112},sticker:{x:s.x,y:s.y,w:s.w||90,h:s.h||90}}}function hit(p){let b=currentBoxes();for(let n of [...zOrder].reverse()){let q=b[n],l=layers[n];if(l.visible&&p.x>=q.x-20&&p.x<=q.x+q.w+20&&p.y>=q.y-20&&p.y<=q.y+q.h+20)return n}return null}
function down(e){if(!photo)return;let p=point(e);push();if(photoAdjust){dragging=true;selected='__photo__';dragOffset={x:p.x-photoDX,y:p.y-photoDY};e.preventDefault();return}let n=hit(p);selected=n;if(n&&n!==locked){dragging=true;dragOffset={x:p.x-layers[n].x,y:p.y-layers[n].y};e.preventDefault()}render()}function move(e){if(!dragging)return;let p=point(e);if(selected==='__photo__'){photoDX=Math.max(-W*.45,Math.min(W*.45,p.x-dragOffset.x));photoDY=Math.max(-H*.45,Math.min(H*.45,p.y-dragOffset.y))}else if(selected){let l=layers[selected];l.x=Math.max(-300,Math.min(W-40,p.x-dragOffset.x));l.y=Math.max(-150,Math.min(H-40,p.y-dragOffset.y))}e.preventDefault();render()}function up(){if(dragging)saveDraft();dragging=false}
canvas.addEventListener('mousedown',down);canvas.addEventListener('mousemove',move);window.addEventListener('mouseup',up);canvas.addEventListener('touchstart',down,{passive:false});canvas.addEventListener('touchmove',move,{passive:false});window.addEventListener('touchend',up);
function scale(d){if(!selected||selected==='__photo__')return alert('请先点选人物、标题、贴纸或 Logo');push();layers[selected].scale=Math.max(.4,Math.min(2.3,layers[selected].scale+d));render();saveDraft()}
$('#smallerBtn').onclick=()=>scale(-.1);$('#largerBtn').onclick=()=>scale(.1);$('#deleteBtn').onclick=()=>{if(!selected||selected==='__photo__')return;push();layers[selected].visible=!layers[selected].visible;render();saveDraft()};$('#frontBtn').onclick=()=>{if(!selected)return;push();zOrder=zOrder.filter(x=>x!==selected).concat(selected);render()};$('#backBtn').onclick=()=>{if(!selected)return;push();zOrder=[selected,...zOrder.filter(x=>x!==selected)];render()};$('#resetLayerBtn').onclick=()=>{if(!selected)return;push();let n=selected;let keep={...layers};resetLayers();keep[n]=layers[n];layers=keep;render()};$('#resetAllBtn').onclick=()=>{push();resetLayers();autoPlace();selected=null;render()};
input.onchange=e=>{let f=e.target.files?.[0];if(!f)return;let u=URL.createObjectURL(f),im=new Image;im.onload=async()=>{photo=im;URL.revokeObjectURL(u);photoZoom=1;photoDX=photoDY=0;await detectPeople(im);pickCombo();resetLayers();autoPlace();await saveImage(f);render();saveDraft()};im.src=u};
$('#courseGrid').onclick=e=>{let b=e.target.closest('[data-course]');if(!b)return;push();course=b.dataset.course;localStorage.popshotLastCourse=course;pickCombo();resetLayers();autoPlace();syncUI();render();saveDraft()};$$('[data-beauty]').forEach(b=>b.onclick=()=>{push();beauty=+b.dataset.beauty;localStorage.popshotLastBeauty=beauty;syncUI();render();saveDraft()});$$('[data-style]').forEach(b=>b.onclick=()=>{push();visualStyle=b.dataset.style;localStorage.popshotStyle=visualStyle;stickerIndex=0;syncUI();render();saveDraft()});$$('[data-density]').forEach(b=>b.onclick=()=>{push();density=b.dataset.density;autoPlace();syncUI();render();saveDraft()});
$('#generateBtn').onclick=()=>{if(!photo)return alert('请先上传照片');push();pickCombo();resetLayers();autoPlace();selected=null;render();saveDraft()};$('#shuffleBtn').onclick=()=>{if(!photo)return;push();pickCombo();resetLayers();autoPlace();selected=null;render();saveDraft()};$('#changeCharacterBtn').onclick=()=>{push();charIndex=(charIndex+1)%6;render()};$('#changeTagBtn').onclick=()=>{push();titleIndex=(titleIndex+1)%titles[course].length;render()};$('#changeStickerBtn').onclick=()=>{push();stickerIndex=(stickerIndex+1)%stickerPool().length;layers.sticker.visible=true;render()};$('#changeFrameBtn').onclick=()=>{push();frameIndex=(frameIndex+1)%4;render()};$('#layoutBtn').onclick=()=>{push();layoutIndex=(layoutIndex+1)%3;resetLayers();if(layoutIndex===0){layers.character.x=70;layers.logo.x=80;layers.title.x=W-80;layers.title.anchor='right'}else if(layoutIndex===2){layers.character.x=W-570;layers.logo.x=W-560;layers.title.x=80;layers.title.anchor='left'}else autoPlace();render()};
$$('[data-candidate]').forEach(b=>b.onclick=()=>{push();let n=+b.dataset.candidate;density=n===0?'simple':n===2?'rich':'normal';layoutIndex=n;resetLayers();autoPlace();$$('[data-candidate]').forEach(x=>x.classList.toggle('active',x===b));syncUI();render()});$('#undoBtn').onclick=()=>{if(!undo.length)return;redo.push(state());restore(undo.pop())};$('#redoBtn').onclick=()=>{if(!redo.length)return;undo.push(state());restore(redo.pop())};$('#lockBtn').onclick=()=>{if(!selected||selected==='__photo__')return alert('请先点选一个元素');locked=locked===selected?null:selected;$('#lockBtn').textContent=locked?'🔒 已锁定':'🔓 锁定当前'};$('#favBtn').onclick=()=>{let f=JSON.parse(localStorage.popshotFavorites||'[]'),k=comboKey();if(!f.includes(k))f.push(k);localStorage.popshotFavorites=JSON.stringify(f.slice(-50));$('#favBtn').textContent='♥ 已收藏'};
const drawer=$('#drawer'),body=$('#drawerBody');$('#drawerClose').onclick=()=>drawer.classList.remove('show');$('#beautyBtn').onclick=()=>{$('#drawerTitle').textContent='美化调整';body.innerHTML=`<div class="range-row"><span>美化强度</span><input id="beautyRange" type="range" min="0" max="100" value="${beauty}"><b>${beauty}</b></div><div class="adjust-tip">仅做基础提亮、对比度与色彩优化，不改变脸型和五官。</div>`;drawer.classList.add('show');$('#beautyRange').oninput=e=>{beauty=+e.target.value;e.target.nextElementSibling.textContent=beauty;render()}};
$('#adjustPhotoBtn').onclick=()=>{photoAdjust=!photoAdjust;selected=null;$('.canvas-stage').classList.toggle('adjusting',photoAdjust);$('#drawerTitle').textContent='调整照片';body.innerHTML=`<div class="range-row"><span>照片缩放</span><input id="zoomRange" type="range" min="100" max="190" value="${Math.round(photoZoom*100)}"><b>${Math.round(photoZoom*100)}%</b></div><div class="adjust-tip">${photoAdjust?'调整模式已开启：直接拖动画面中的照片即可移动位置。':'点击“调整照片”再次开启拖动。'} 自动裁剪只是默认建议，最终位置完全可以人工决定。</div><button id="cropReset" class="ghost" style="margin-top:10px">恢复智能裁剪</button>`;drawer.classList.add('show');$('#zoomRange').oninput=e=>{photoZoom=+e.target.value/100;e.target.nextElementSibling.textContent=e.target.value+'%';render();saveDraft()};$('#cropReset').onclick=()=>{photoZoom=1;photoDX=photoDY=0;render();saveDraft()}};
function updateCheck(){if(!photo)return;let h=holidayStickers(),txt=`✓ 2525×1894 · ${boxesDetected.length?'主体识别 '+boxesDetected.length+' 人':'智能裁剪'} · ${h?'节日素材已开启':'通用素材模式'}`;$('#exportCheck').textContent=txt;$('#exportCheck').classList.add('ok')}
$('#exportBtn').onclick=async()=>{if(!photo)return alert('请先上传照片');selected=null;photoAdjust=false;$('.canvas-stage').classList.remove('adjusting');await render();let a=document.createElement('a');a.download=`PopShot-${course}-${Date.now()}.jpg`;a.href=canvas.toDataURL('image/jpeg',.96);a.click()};
function saveDraft(){if(photo)localStorage.popshotDraftState=state()}function openDB(){return new Promise((r,j)=>{let q=indexedDB.open('PopShotDB',1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains('draft'))q.result.createObjectStore('draft')};q.onsuccess=()=>r(q.result);q.onerror=()=>j(q.error)})}async function saveImage(file){try{let db=await openDB(),tx=db.transaction('draft','readwrite');tx.objectStore('draft').put(file,'photo')}catch{}}async function loadImage(){try{let db=await openDB();return await new Promise(r=>{let q=db.transaction('draft').objectStore('draft').get('photo');q.onsuccess=()=>r(q.result||null);q.onerror=()=>r(null)})}catch{return null}}async function clearDraft(){try{let db=await openDB();db.transaction('draft','readwrite').objectStore('draft').delete('photo')}catch{}localStorage.removeItem('popshotDraftState')}
async function resume(){let raw=localStorage.popshotDraftState,blob=await loadImage();if(!raw||!blob)return;$('#resumeModal').classList.remove('hidden');$('#continueResume').onclick=()=>{let u=URL.createObjectURL(blob),im=new Image;im.onload=async()=>{photo=im;URL.revokeObjectURL(u);await detectPeople(im);restore(raw);$('#resumeModal').classList.add('hidden')};im.src=u};$('#discardResume').onclick=async()=>{$('#resumeModal').classList.add('hidden');await clearDraft()}}
$('#updateBtn').onclick=()=>$('#updateTip').classList.remove('hidden');$('#closeUpdateTip').onclick=()=>$('#updateTip').classList.add('hidden');$('#settingsBtn').onclick=()=>alert('PopShot v8 · 照片仅在本机浏览器处理');
if('serviceWorker'in navigator)navigator.serviceWorker.register('./service-worker.js?v=8').catch(()=>{});syncUI();resume();
